language: go

go:
  - 1.10.2
env:
  secure: "djoUjH9PizMkQV8n8HkNBmnHGOKcSG5nzJJhi20RSo7p+S4sxkgh1Inc3MfZhNUksx0FI3Amch3ER4E4penDfKrceQR2kl7MdOYC/th4nL10ClDev8D+/gY7mkqyLJhK1WUQz9+QROynJeXABW9RFD5/HhLcAVHw+bo9MVP+7Ekghu0+5JGbtYknisdfUAWspAyOe+M3m4IuTlpleaanu64GsxLYp5CnSucvT6wkSIiKpNd9v965qJyk9XxBBD3mDGI9Alr3v26K98U2zXGbMd22XBEMmZOnFsuLdj2U14ZHZYZV0JVKLZEj4w9r/v1OM953PdS++iz6xsVyjil9ey+OzZZ5YnPXrl/G2z1s2AKbhAG2tXsBE7Spmu2itKfQP1xCgxL71Asb5b2oVTjSRhiw3votUTXHLBmDSM6PI84m5xkLsRiyt+4cYlorCZ1yfyQt7lyioAwuypv9gZz1j679Ft01m0sTVY4MO2cDDdI1+YOmzbtazXVNOTzv+Gs+M8LYZDYN5sMV7IzYMqzDQxcXzac9oS8gldzIhaafs0gscvcotVbr8m0PpkRaOgcBBSJ20F9S6DQ+LDrrwOGxGHTMFsa52VHA3bhBNKoolgEQHttnl2Acz3hp9IyqG1O33b6NEWuFzpFuzzQ/YaH6VVqmJHnmXZIvru+CBgBcxEY="
  secure: "V/LT45XRY23Nz1P2rfrV+0myZiiYzrUhUf+FNYwzCbK54gyfoOrkXryOSrPpaOQMJO00KLwGHjtjkKIhimOyTL5i/OV9P4tMamla9O5kf2Iefx9DZWFjP39WLYyPancVPMVQKx7pclqN6B98Z4y6Sz1rl8Nte25rSNoHuNF2Ke+3EJwesRQ/MXDpol5IPZbjifZ9UmdMfSfHcNxi6g2uzRz85Ul55m8bk8zJ7y9LGSXT55l/xMMjKy3BROqhhjNsHwcph2IuxBTtLacKa7MPHkW9w52gVWeJ37GcWvr4VmikHJNFyi6F21c+bu9Iev09Oq6TjpXUs4PLYlA3ch/DMkCjNSaYN2mPiE2K7QMDNPLjzQNjoxijh7Y/hTmjVIjAA7AbbzxutiENdWrFdZWbqgjOcRB6pUqmopKYV8RwTRwUJ8S2jo61QedH+iEPce7O5KTpUk6UC0qYeF/zkEXh0QBnGaiVH+iwj6xFgzXMrNF93Tu1Ydo3IF94kT0jCiVNuDhyn+wURupIelyjOFevRrw9lbHdY3CAcq5hhDoOu+bUAxay88U07nIn4KQH2WfiZWgMAI80inVGMMbZayR2+0HuUFHgw1I5+aXlZofcsumN88OjDCyRJA9tqb0g82irgmu/AryzT4cUJHxzMdUh3OdXvRlCvsEqdZJGLgLE5ew="
install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
script:
  - go test -v -covermode=count -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
  - go build .
