language: go

go:
  - 1.10.2
install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
script:
  - go test -v -covermode=count -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
  - go build .
env:
  global:
  - secure: L11sTgurtyw3PaAzHkX+hSjPmqxYmAPk6GWlfcmRPvsiPN1PSdXT3LG+nnSYj0lCAynIF7tr6oIPZh+FLWOxpnpORKj2t776fXeUH9QPNLfgb/rSiolkdn/2wu+wWiLIST/Ml1EgIwaWkVjZFQJ2WYwKh048K0MBa3EZzso/1D1nmuplitJwS0q1d1vR2JYLjx+WIfxWjutsyHSLWa/JWhFSPi/BbNyEzRxUDl6pIBeh9Y9srbYq6lFcxOXe5CQbebFrUtTv44I9CZIt76vl3umpJmYCilILG93gkwb7eJaHbe49RSTCUvDsLRzgbr04WazcbY611seVkmg4MuwUFtNmAxLOKL+6Bwn5cWmHeAPix1OffYWLNVr5LrAwB2fXR9A5Ikg3hjQbyiBpJIlnt/PeIdj+umeAlcltcvddq/hScGoKKkQJFab/v+M6NqOh3HZVXuK5BqKpmgrDYohEsaCuLWdUy5wkMvaDMJpsXHT9X2wE7gKMRlD9Xkz8BKYzRtFbIiotnHkbTaJr8HqTNmDoy/j3C3q/SIuDRivUdI2ISFsL82ZK7wgeV4peef/Ta3SGyVmEpAC2tgOU5PHU++Stmrj0Wk+Pjzhb5gSYme4jR2BYD9QWQt63zm6Kg2+aTZE72EaSn7CCJwVQW8RpvvjIDZwyaPLVnkQzepJ1LrE=
  - secure: Rp7VuCLCs2Jrb4rNPqZ3SVOGG5OuEOJEoQUeYTqJqS2ACAtd67AHkNZtx8pEs+wJM3ZbiuqelP2lpZrBuTTN9Xsi9bcMFlbETu1/cGWRFPfJqJ/ZbAjSWafkZGrJKdznldXtVwCiY0fTDz1uFwWm4QbooG8LAkKA5OOc9bq0MYcDFEvtd0zAHGvnBlMI6oK5MGp1hvzcOr4htd1saNEDSR5bSPTXfPxFch/iskeeLnUvf4mqM+QgGUdXHz4QRb6Pj10pCESQqV3MX4nX79xgkCKYX4jqCi5sp0bhwHgusr+8zW9KNa+6a0jPhu954d4/VQyKvW8bwPTlj1A9GXAHRGrlWTuCwcOMxnjFb/HUq/r/HFAiA2pOitOg5+OgdZL2U03LnoEDJNiFo7EIzdpMDwsAz29p9X9MYK+ivBBvZ5XeVO7vwVKroWepbWZ+uq4RLzpOh2tj4/fnHUrgxbhxgl33pw44WkowVniltFl5rAwpyaZExORdmzX4jzduyiXsG9r5cLnb152DoJFvSZWsgfYWwYz/C99Ioh9tgY3rSNR+ncKNsWHBmUED887CPtgeL/mrrPm6llU9j9mAxhzqpwzgXnundro36JDh7p/zBeA4PdqZgOmErL6acEZjWMOiLQnRrB2E60Pl7Fpe1ICYFN1O/CIurfsD+nrOoWj1u2E=
